services:
  db:
    container_name: infovita-db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - 5432:5432
    volumes:
      - db-vol:/var/lib/postgresql/data

  pgadmin:
    container_name: infovita-pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=12345
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050
    volumes:
      - pgadm-vol:/var/lib/pgadmin

volumes:
  db-vol:
  pgadm-vol:
