spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/infovita
    username: postgres
    password: 12345

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  jackson:
    serialization:
      WRITE-DATES-AS-TIMESTAMPS: true

error:
  include:
    stack-trace: on-param