spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    serialization:
      WRITE-DATES-AS-TIMESTAMPS: true

error:
  include:
    stack-trace: on-param